repos:
  - repo: local
    hooks:
      - id: generate-requirements
        name: Generate requirements.txt from requirements.lock and add to git
        entry: bash -c './scripts/generate-requirements.sh'
        language: system
        always_run: true
        pass_filenames: false

